### ISSUE TITLE
Student Application - Questionnaire

### ISSUE THREAD

**Issue by bjablonsky** [dotnet-foundation/wg-education#10]
All fields will be text boxes unless otherwise stated.

Below is a list of questions we will ask the students to fill out for the application process:
- First Name
- Last Name
- Email (please use your school's .EDU address)
- What Country do you reside in?
- What City/State/Province do you live in?
- Are you willing to attend the class during the Eastern Standard Time (UTC-5) between 6PM and 9PM? (Yes/No Question)
- College/University/School you attend
- Major (optional)
- How many years of higher education schooling have you completed?
- What programming language is primarily being taught at your institution?
- Age (optional)
- Preferred Pronouns (optional)
- Race or ethnicity (search around) (optional)
- Link to GitHub (optional)
- Link to LinkedIn (optional)
- Have you completed a class on object oriented programming? (yes/no)
- Have you completed a class on data structures? (yes/no)
- Have you completed a class on algorithms? (yes/no)
- Please tell us which programming languages you've used?
- Which language are you most comfortable with?
- Why do you want to join the DNF Academy and learn .NET?
- What do you hope to get out of the program?
- Where did you hear about the DNF Academy?
- What other programming-related extra curricular opportunities (like clubs, competitions, etc) does your college/university/school offer you?
- Anything else you would like to let us know about yourself?

**Comment by RichardHowells** [comment]
I looked at the form link @bjablonsky sent during the meeting last night.  Is the source of that available on github?  I was going to submit a PR because I spotted a few spellies etc in it.

Now I can't find the link to look again.

**Comment by bjablonsky** [comment]
Here's a link to the survey: https://forms.office.com/Pages/DesignPage.aspx?origin=OfficeDotCom&lang=en-US&route=Start#FormId=3G8HFsH8FUqxyjLJolWQDmVvV45L2FRBqqwjagiFEH1UOE1URDJLSUtWUUtPMFBaSENETzQyUjI5WC4u

**Comment by RichardHowells** [comment]
It told me that I didn't have permission to edit it.

**Comment by saitorhan** [comment]
It told me that I didn't have permission to edit it.

**Comment by bjablonsky** [comment]
Apologies. I updated the URL.

**Comment by RichardHowells** [comment]
A few tiny feedback items.

8 - for 'what is' read 'what are'
12 for 'your' read 'you'
13 - maybe remove 'being'

**Comment by RichardHowells** [comment]
Major feedback - the form requests personally identifiable information and as such needs some kind of review (which I am not qualified to do) for GDPR compliance.

**Comment by bjablonsky** [comment]
Fixed the typos. Thanks @RichardHowells!

For GDPR, from my understanding, we should be covered since the membership is covered under GDPR. I'm double checking with the board.

**Comment by bjablonsky** [comment]
Spoke with the board, and added a disclaimer to the questionnaire that should cover us. Thanks @RichardHowells @saitorhan for the feedback!

Closing this since we launched the application.
