### ISSUE TITLE
Join Request

### ISSUE THREAD

**Issue by suchja** [dotnet-foundation/wg-education#29]
Hi, I would like to support this working group.

I'm a senior .NET developer and instructor for teaching people the first steps with .NET and C#. I would love to support this project.

**Comment by frankodoom** [comment]
@suchja  please fill out our membership [form](https://forms.office.com/r/uf3HLLevAK) to receive a meeting invitation. we will love you to share your experience and contributions as a member of the committee. Hope to see you in our meetings,
