### ISSUE TITLE
Join request

### ISSUE THREAD

**Issue by PadreSVK** [dotnet-foundation/wg-education#30]
Hi, I am a developer and instructor. I would like to join and support this working group.

**Comment by nicoleabuhakmeh** [comment]
Adding Frank as chair

**Comment by frankodoom** [comment]
Hi @PadreSVK  Please fill out our membership [form](https://forms.office.com/r/uf3HLLevAK) to receive a meeting invitation. We are looking forward to have people of your background join the committee, We will love to hear your contributions and views.

**Comment by PadreSVK** [comment]
@frankodoom form filled 🙂

**Comment by PadreSVK** [comment]
@frankodoom hi, sorry I was declining today's meeting and that meeting won't appear anymore in my calendar. Should I reapply that form? :)
