### ISSUE TITLE
Join request

### ISSUE THREAD

**Issue by SpaceShot** [dotnet-foundation/wg-education#31]
I'd like to join the group and come by the Teams meetings and help understand the needs for curriculum programs.  I also noted that the link on the README.md to join the education team doesn't work.  I can submit a PR to fix it, but I am wondering what exactly it is supposed to do.

Thank you

**Comment by nicoleabuhakmeh** [comment]
Hi Chris, 

I've added the Chair for the committee to this issue.  He should be able to add you to the meeting. @frankodoom - at Friday's sync, I'll see if there is a list we can gather moving forward.

**Comment by frankodoom** [comment]
@SpaceShot Fill out our membership [form](https://forms.office.com/r/uf3HLLevAK) to receive a meeting invitation. you are always welcome to make contributions to the committee's repository. Hope to see you on one of our meetings, We will love to have your contributions and views.
