### ISSUE TITLE
Create landing page

### ISSUE THREAD

**Issue by bjablonsky** [dotnet-foundation/wg-education#9]
Create a landing page either on the DNF website or micro site

**Comment by huunab** [comment]
@bjablonsky Hi, I know you have already done this, but would you mid sharing with me an image so I can potentially propose a UI enhancement?

**Comment by bjablonsky** [comment]
Apologies @huunab. I didn't see this comment earlier. We launched the website. Feel free to take a look and re-open this issue with any fixes/tweaks/changes: [https://dotnetfoundation.org/education/academy](https://dotnetfoundation.org/education/academy).

Closing this issue since we launched the website.
